apiVersion: v1
kind: Namespace
metadata:
  name: keeper
  labels:
    name: keeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper-backend-deploy
  namespace: keeper
  labels:
    app: keeper-backend
spec:
  selector:
    matchLabels:
      app: keeper-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: keeper-backend
    spec:
      containers:
        - name: keeper-backend
          image: hannguyendev/keeper-be:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keeper-frontend-deploy
  namespace: keeper
  labels:
    app: keeper-frontend
spec:
  selector:
    matchLabels:
      app: keeper-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: keeper-frontend
    spec:
      containers:
        - name: keeper-frontend
          image: hannguyendev/keeper-fe:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: keeper-backend-service
  namespace: keeper
spec:
  selector:
    app: keeper-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keeper-frontend-service
  namespace: keeper
spec:
  selector:
    app: keeper-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001

